config/routes.rb
Rails.application.routes.draw do
  resources :reviews
  get 'show_tour_review' => 'reviews#show_tour_review'
  resources :bookings
  get 'my_bookings' => 'bookings#my_bookings'
  get 'my_customers_booked' => 'bookings#my_customers_booked'
  get 'my_customers_bookmarked' => 'bookings#my_customers_bookmarked'
  get 'new_with_waitlist' => 'bookings#new_with_waitlist'
  get 'bookmark' => 'bookings#bookmark'
  get 'undo_bookmark' => 'bookings#undo_bookmark'
  get 'customer_bookmarks' => 'bookings#customer_bookmarks'
  get 'agent_bookmarks' => 'bookings#agent_bookmarks'
  resources :tours
  resources :tours do
    resources :reviews, except: [:show, :index]
    member do
      patch :cancel_tour
      put :cancel_tour
    end
  end
  get 'search' => 'tours#search'
  get 'image' => 'tours#image'

  get 'home/index'

  devise_for :users
  resources :users, except: :create
  post 'create_user' => 'users#create', as: :create_user
  get 'admin' => 'users#admin'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'home#index'
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :tour
  validates :booked_seats, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :booked_seats, presence: true, numericality: { greater_than: 0 }, if: :both_missing?
  validates :waitlist_seats, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :waitlist_seats, presence: true, numericality: { greater_than: 0 }, if: :both_missing?
  validates :user_id, presence: true
  validates :tour_id, presence: true
  validate :seats_availability
  after_destroy :fill_available_seats


  def find_booked_tour
    Tour.find(self.tour_id)
  end

  def find_agent_id_of_tour
    find_booked_tour.user_id
  end

  def find_customer
    User.find(self.user_id)
  end

  def fill_available_seats
    this_tour = find_booked_tour
    if this_tour.get_waitlist > 0 && this_tour.available_seats > 0
      Booking.where("tour_id = ?", this_tour.id).find_each do |customer|
        if customer.waitlist_seats > 0 && customer.waitlist_seats <= this_tour.available_seats
          taken_seats = customer.booked_seats
          customer.update_attribute(:booked_seats, taken_seats + customer.waitlist_seats)
          customer.update_attribute(:waitlist_seats, 0)
        end
      end
    end

    if this_tour.get_waitlist > 0 && this_tour.available_seats > 0
      Booking.where("tour_id = ?", this_tour.id).find_each do |customer|
        if customer.waitlist_seats > 0
          new_waitlist = customer.waitlist_seats - this_tour.available_seats
          taken_seats = customer.booked_seats
          customer.update_attribute(:booked_seats, taken_seats + this_tour.available_seats)
          customer.update_attribute(:waitlist_seats, new_waitlist)
          break
        end
      end
    end
  end

  private
    def both_missing?
      self.booked_seats = 0 if self.booked_seats.nil?
      self.waitlist_seats = 0 if self.waitlist_seats.nil?
      if self.booked_seats.zero? && self.waitlist_seats.zero? && !self.bookmark
        errors.add 'Error:', "Cannot Book unspecified number of seats for the Tour"
      end
    end

  private
    def seats_availability
      tour = find_booked_tour
      errors.add tour.name, "Cannot Book #{tour.show_status} tour" unless tour.show_status == "In Future" || self.bookmark
      if tour.total_seats < self.booked_seats
        errors.add tour.name, "Cannot Book #{self.booked_seats} with only #{tour.total_seats} total seats in the tour."
      end
      if tour.total_seats < self.booked_seats + self.waitlist_seats
        errors.add tour.name, "Cannot Book and Wait list #{self.booked_seats + self.waitlist_seats} seats with only #{tour.total_seats} total seats in the tour."
      end
    end

end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_booking, only: [:get, :show, :edit, :update, :destroy]

  # GET /bookings
  # GET /bookings.json
  def index
    @bookings = Booking.all
  end

  # GET /bookings/1
  # GET /bookings/1.json
  def show
    @bookings = Booking.find(params[:id])
  end

  # GET /bookings/new
  def new
    @booking = Booking.new
  end

  def new_with_waitlist
    @booking = Booking.new
  end

  # GET /bookings/1/edit
  def edit
  end

  # POST /bookings
  # POST /bookings.json
  def create
    @booking = Booking.new(booking_params)
    tour = Tour.find(params[:tour_id])
    @booking.user_id = current_user.id
    @booking.tour_id = tour.id
    @booking.booked_seats = 0 if @booking.booked_seats.nil?
    @booking.waitlist_seats = 0 if @booking.waitlist_seats.nil?
    booking = tour.find_booking(current_user.id)

    respond_to do |format|
      if tour.available_seats < @booking.booked_seats
        format.html { redirect_to new_with_waitlist_path(tour_id: tour.id, default_booked_seats: tour.available_seats, default_waitlist_seats: @booking.waitlist_seats + @booking.booked_seats - tour.available_seats), alert: 'Not enough available seats to Book.' }
      elsif !booking.nil? && !booking.blank?
        booking.update_attributes(booked_seats: @booking.booked_seats, waitlist_seats: @booking.waitlist_seats, created_at: Time.now)
        format.html { redirect_to booking, notice: 'Booking was successfully created.' }
        format.json { render :show, status: :created, location: booking }
      elsif @booking.save
        format.html { redirect_to @booking, notice: 'Booking was successfully created.' }
        format.json { render :show, status: :created, location: @booking }
      else
        format.html { render :new }
        format.json { render json: @booking.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bookings/1
  # PATCH/PUT /bookings/1.json
  def update
    tour = Tour.find(params[:tour_id])

    respond_to do |format|
      if tour.available_seats + @booking.booked_seats < booking_params[:booked_seats].to_i
        format.html { redirect_to edit_booking_url(@booking, tour_id: @booking.find_booked_tour.id, default_booked_seats: tour.available_seats + @booking.booked_seats, default_waitlist_seats: booking_params[:booked_seats].to_i + booking_params[:waitlist_seats].to_i - tour.available_seats - @booking.booked_seats), alert: 'Not enough available seats to Book.' }
      elsif @booking.update(booking_params)
        @booking.fill_available_seats
        format.html { redirect_to @booking, notice: 'Booking was successfully updated.' }
        format.json { render :show, status: :ok, location: @booking }
      else
        format.html { render :edit }
        format.json { render json: @booking.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bookings/1
  # DELETE /bookings/1.json
  def destroy
    if @booking.bookmark
      @booking.booked_seats = 0
      @booking.waitlist_seats = 0
      @booking.update_attributes(booked_seats: @booking.booked_seats, waitlist_seats: @booking.waitlist_seats)
      @booking.fill_available_seats
      respond_to do |format|
        format.html { redirect_to my_bookings_url, notice: 'Booking was successfully destroyed.' }
        format.json { head :no_content }
      end
    else
      @booking.destroy
      respond_to do |format|
        format.html { redirect_to my_bookings_url, notice: 'Booking was successfully destroyed.' }
        format.json { head :no_content }
      end
    end
  end

  # GET /my_bookings
  # GET /my_bookings.json
  def my_bookings
    @bookings = Booking.all
  end

  # GET /my_customers_booked
  # GET /my_customers_booked.json
  def my_customers_booked
    @bookings = Booking.where(tour_id: params[:tour_id])
    @tour = Tour.find_by(id: params[:tour_id])
  end

  # GET /my_customers_bookmarked
  # GET /my_customers_bookmarked.json
  def my_customers_bookmarked
    @bookings = Booking.where(tour_id: params[:tour_id])
    @tour = Tour.find_by(id: params[:tour_id])
  end

  # GET /bookmark
  # GET /bookmark.json
  def bookmark
    if params[:tour_id].nil? || params[:tour_id].blank?
      respond_to do |format|
        format.html { redirect_to tours_url, alert: 'Unchecked Tours cannot be Bookmarked!!!' }
        format.json { render get, status: :ok, location: tours_url }
      end
    else
      params[:tour_id].each do |tour_id|
        booking = Booking.find_by(user_id: current_user.id, tour_id: tour_id)
        if booking.nil? || booking.blank?
          Booking.create!(booked_seats: 0, user_id: current_user.id, tour_id: tour_id, waitlist_seats: 0, bookmark: true)
        else
          booking.update_attribute(:bookmark, true)
        end
      end
      respond_to do |format|
        if params[:tour_id].length == 1
          format.html { redirect_to Tour.find(params[:tour_id]), notice: 'Tour was successfully Bookmarked.' }
          format.json { render :show, status: :ok, location: Tour.find(params[:tour_id]) }
        else
          format.html { redirect_to tours_url, notice: 'Tours were successfully Bookmarked.' }
          format.json { render :get, status: :ok, location: tours_url }
        end
      end
    end
  end

  # GET /undo_bookmark
  # GET /undo_bookmark.json
  def undo_bookmark
    if params[:tour_id].nil? || params[:tour_id].blank?
      respond_to do |format|
        format.html { redirect_to customer_bookmarks_url, alert: 'Unchecked Tours cannot be Unbookmarked!!!' }
        format.json { render get, status: :ok, location: tours_url }
      end
    else
      params[:tour_id].each do |tour_id|
        booking = Booking.find_by(user_id: current_user.id, tour_id: tour_id)
        booking.update_attribute(:bookmark, false)
        if booking.booked_seats.zero? && booking.waitlist_seats.zero?
          booking.destroy
        end
      end
      respond_to do |format|
        format.html { redirect_to customer_bookmarks_url, notice: 'Unbookmark is successful.' }
        format.json { render :get, status: :ok, location: customer_bookmarks_url }
      end
    end
  end

  # GET /customer_bookmarks
  # GET /customer_bookmarks.json
  def customer_bookmarks
    @bookings = Booking.all
  end

  # GET /agent_bookmarks
  # GET /agent_bookmarks.json
  def agent_bookmarks
    @bookings = Booking.all
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_booking
      @booking = Booking.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def booking_params
      params.require(:booking).permit(:booked_seats, :waitlist_seats, :user_id, :tour_id)
    end
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/views/bookings/_form.html.erb
<%= form_with(model: booking, local: true) do |form| %>
  <% if booking.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(booking.errors.count, "error") %> prohibited this booking from being saved:</h2>

      <ul>
      <% booking.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <p>
      <strong>Tour name:</strong>
      <%= Tour.find(params[:tour_id]).name %>
    </p>
  </div>

  <div class="field">
    <%= form.label :booked_seats %>
    <%= form.number_field :booked_seats %>
  </div>

  <div class="actions">
    <%= hidden_field_tag 'tour_id', params[:tour_id] %>
    <%= form.submit data: { confirm: 'Confirm to Book' } %>
  </div>
<% end %>

app/views/bookings/_form_with_waitlist.html.erb
<%= form_with(model: booking, local: true) do |form| %>
  <% if booking.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(booking.errors.count, "error") %> prohibited this booking from being saved:</h2>

      <ul>
      <% booking.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <p>
      <strong>Tour name:</strong>
      <%= Tour.find(params[:tour_id]).name %>
    </p>
    <p>
      <strong> Available Seats:</strong>
      <%= Tour.find(params[:tour_id]).available_seats %>
    </p>
    <p>
      <strong>Total Seats:</strong>
      <%= Tour.find(params[:tour_id]).total_seats %>
    </p>
  </div>

  <div class="field">
    <%= form.label 'Book Seats for the Tour (Note: if you leave it blank or 0, you will book NO seats)' %>
    <%= form.number_field :booked_seats, value: params[:default_booked_seats] || form.object.booked_seats %>
  </div>

  <div class="field">
    <%= form.label 'Place seats in the Wait List' %>
    <%= form.number_field :waitlist_seats, value: params[:default_waitlist_seats] || form.object.waitlist_seats %>
  </div>

  <div class="actions">
    <%= hidden_field_tag 'tour_id', params[:tour_id] %>
    <%= form.submit 'Book/Wait List', data: { confirm: 'Confirm Booking/Wait List' } %>
  </div>
<% end %>

app/views/bookings/agent_bookmarks.erb
<p id="notice"><%= notice %></p>

<h1>List of All Customers Bookmarked My Tours</h1>

<table>
  <thead>
    <tr>
      <th>Customer name</th>
      <th>Customer email</th>
      <th>Tour name</th>
      <th>Tour price</th>
      <th>Tour start location</th>
      <th>Tour start date</th>
      <th>Tour end date</th>
      <th>Tour status</th>
      <th>Available seats</th>
      <th>Wait list</th>
      <th>Total seats</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @bookings.each do |booking| %>
      <% if current_user.id == booking.find_agent_id_of_tour && booking.bookmark %>
        <tr>
          <td><%= booking.find_customer.name %></td>
          <td><%= booking.find_customer.email %></td>
          <td><%= booking.find_booked_tour.name %></td>
          <td><%= booking.find_booked_tour.price %></td>
          <td><%= booking.find_booked_tour.start_location %></td>
          <td><%= booking.find_booked_tour.start_date %></td>
          <td><%= booking.find_booked_tour.end_date %></td>
          <td><%= booking.find_booked_tour.show_status %></td>
          <td><%= booking.find_booked_tour.available_seats %></td>
          <td><%= booking.find_booked_tour.get_waitlist %></td>
          <td><%= booking.find_booked_tour.total_seats %></td>
          <td><%= link_to 'Show Tour', booking.find_booked_tour %></td>
          <td><%= link_to 'Show Customer', booking.find_customer %></td>
          <td><%= link_to 'Edit Tour', edit_tour_url(booking.find_booked_tour) %></td>
         </tr>
      <% end %>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Home', home_index_url %> |
<%= link_to 'Back', home_index_url %>

app/views/bookings/customer_bookmarks.erb
<p id="notice"><%= notice %></p>

<%= form_tag(undo_bookmark_url, method: :get)  do %>
  <h1>My Bookmarked Tours</h1>

  <table>
    <thead>
      <tr>
        <th>Undo Bookmark</th>
        <th>Tour name</th>
        <th>Tour price</th>
        <th>Tour start location</th>
        <th>Tour start date</th>
        <th>Tour end date</th>
        <th>Tour status</th>
        <th>Booked seats</th>
        <th>My wait list</th>
        <th>Tour Available seats</th>
        <th>Tour Wait list</th>
        <th>Tour total seats</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @bookings.each do |booking| %>
        <% if current_user.id == booking.user_id && booking.bookmark %>
          <tr>
            <td><%= check_box_tag 'tour_id[]', booking.find_booked_tour.id %></td>
            <td><%= booking.find_booked_tour.name %></td>
            <td><%= booking.find_booked_tour.price %></td>
            <td><%= booking.find_booked_tour.start_location %></td>
            <td><%= booking.find_booked_tour.start_date %></td>
            <td><%= booking.find_booked_tour.end_date %></td>
            <td><%= booking.find_booked_tour.show_status %></td>
            <td><%= booking.booked_seats %></td>
            <td><%= booking.waitlist_seats %></td>
            <td><%= booking.find_booked_tour.available_seats %></td>
            <td><%= booking.find_booked_tour.get_waitlist %></td>
            <td><%= booking.find_booked_tour.total_seats %></td>
            <td><%= link_to 'Show Tour', booking.find_booked_tour %></td>
          </tr>
        <% end %>
      <% end %>
    </tbody>
  </table>
  <%= submit_tag 'Undo bookmark' %>
<% end %>

<br>

<%= link_to 'Home', home_index_url %> |
<%= link_to 'Back', home_index_url %>

app/views/bookings/edit.html.erb
<h1>Editing Booking</h1>

<%= render 'form', booking: @booking %>

<%= link_to 'Show', @booking %> |
<%= link_to 'Back', my_bookings_path %>

app/views/bookings/edit_waitlist.html.erb
<h1>Editing My Wait List</h1>

<%= render 'form_with_waitlist', booking: @booking %>

<%= link_to 'Show', @booking %> |
<%= link_to 'Back', my_bookings_path %>

app/views/bookings/index.html.erb
<p id="notice"><%= notice %></p>

<h1>List of All Customers Booked My Tours</h1>

<table>
  <thead>
    <tr>
      <th>Customer name</th>
      <th>Customer email</th>
      <th>Customer booked seats</th>
      <th>Customer wait list seats</th>
      <th>Tour name</th>
      <th>Tour price</th>
      <th>Tour start location</th>
      <th>Tour start date</th>
      <th>Tour end date</th>
      <th>Tour status</th>
      <th>Available seats</th>
      <th>Wait list</th>
      <th>Total seats</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @bookings.each do |booking| %>
      <% if current_user.id == booking.find_agent_id_of_tour %>
        <% if !booking.booked_seats.zero? || !booking.waitlist_seats.zero? %>
          <tr>
            <td><%= booking.find_customer.name %></td>
            <td><%= booking.find_customer.email %></td>
            <td><%= booking.booked_seats %></td>
            <td><%= booking.waitlist_seats %></td>
            <td><%= booking.find_booked_tour.name %></td>
            <td><%= booking.find_booked_tour.price %></td>
            <td><%= booking.find_booked_tour.start_location %></td>
            <td><%= booking.find_booked_tour.start_date %></td>
            <td><%= booking.find_booked_tour.end_date %></td>
            <td><%= booking.find_booked_tour.show_status %></td>
            <td><%= booking.find_booked_tour.available_seats %></td>
            <td><%= booking.find_booked_tour.get_waitlist %></td>
            <td><%= booking.find_booked_tour.total_seats %></td>
            <td><%= link_to 'Show Tour', booking.find_booked_tour %></td>
            <td><%= link_to 'Show Customer', booking.find_customer %></td>
            <td><%= link_to 'Edit Tour', edit_tour_url(booking.find_booked_tour) %></td>
          </tr>
        <% end %>
      <% end %>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Home', home_index_url %> |
<%= link_to 'Back', home_index_url %>

app/views/bookings/my_bookings.html.erb
<p id="notice"><%= notice %></p>

<h1>My Bookings</h1>

<table>
  <thead>
    <tr>
      <th>Tour name</th>
      <th>Tour price</th>
      <th>Tour start location</th>
      <th>Tour start date</th>
      <th>Tour end date</th>
      <th>Tour status</th>
      <th>Booked seats</th>
      <th>My wait list</th>
      <th>Tour Available seats</th>
      <th>Tour Wait list</th>
      <th>Tour total seats</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @bookings.each do |booking| %>
      <% if current_user.id == booking.user_id && (!booking.booked_seats.zero? || !booking.waitlist_seats.zero?) %>
        <tr>
          <td><%= booking.find_booked_tour.name %></td>
          <td><%= booking.find_booked_tour.price %></td>
          <td><%= booking.find_booked_tour.start_location %></td>
          <td><%= booking.find_booked_tour.start_date %></td>
          <td><%= booking.find_booked_tour.end_date %></td>
          <td><%= booking.find_booked_tour.show_status %></td>
          <td><%= booking.booked_seats %></td>
          <td><%= booking.waitlist_seats %></td>
          <td><%= booking.find_booked_tour.available_seats %></td>
          <td><%= booking.find_booked_tour.get_waitlist %></td>
          <td><%= booking.find_booked_tour.total_seats %></td>
          <td><%= link_to 'Details', booking %></td>
          <td><%= link_to 'Show Tour', booking.find_booked_tour %></td>
          <td><%= link_to 'Edit Booking', edit_booking_url(booking, tour_id: booking.find_booked_tour.id) %></td>
          <td><%= link_to 'Delete Booking', booking, method: :delete, data: { confirm: 'Are you sure to delete Booking?' } %></td>
        </tr>
      <% end %>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Home', home_index_url %> |
<%= link_to 'Create New Booking', tours_path %> |
<%= link_to 'Back', home_index_url %>

app/views/bookings/my_customers_booked.html.erb
<p id="notice"><%= notice %></p>

<h1>Customers Booked My Tour <%= @tour.name %></h1>

<table>
  <thead>
  <tr>
    <th>Customer name</th>
    <th>Customer email</th>
    <th>Tour name</th>
    <th>Booked Seats</th>
    <th>Customer Wait List Seats</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <% @bookings.each do |booking| %>
    <% if !booking.booked_seats.zero? || !booking.waitlist_seats.zero? %>
      <% if current_user.admin? || (current_user.id == booking.find_agent_id_of_tour && @tour.id == booking.tour_id) %>
        <tr>
          <td><%= booking.find_customer.name %></td>
          <td><%= booking.find_customer.email %></td>
          <td><%= booking.find_booked_tour.name %></td>
          <td><%= booking.booked_seats %></td>
          <td><%= booking.waitlist_seats %></td>
          <td><%= link_to 'Show Customer', booking.find_customer %></td>
        </tr>
      <% end %>
    <% end %>
  <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Home', home_index_url %> |
<%= link_to 'Back to Tours', tours_url %>

app/views/bookings/my_customers_bookmarked.html.erb
<p id="notice"><%= notice %></p>

<h1>Customers Bookmarked My Tour <%= @tour.name %></h1>

<table>
  <thead>
  <tr>
    <th>Customer name</th>
    <th>Customer email</th>
    <th>Tour name</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <% @bookings.each do |booking| %>
    <% if current_user.admin? || (current_user.id == booking.find_agent_id_of_tour && @tour.id  == booking.tour_id && booking.bookmark) %>
      <tr>
        <td><%= booking.find_customer.name %></td>
        <td><%= booking.find_customer.email %></td>
        <td><%= booking.find_booked_tour.name %></td>
        <td><%= link_to 'Show Customer', booking.find_customer %></td>
      </tr>
    <% end %>
  <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Home', home_index_url %> |
<%= link_to 'Back to Tours', tours_url %>

app/views/bookings/new.html.erb
<h1>New Booking for Tour "<%= Tour.find(params[:tour_id]).name %>" </h1>

<%= render 'form', booking: @booking %>

<%= link_to 'Back', my_bookings_path %>

app/views/bookings/new_with_waitlist.html.erb
<h1>New Booking for Tour "<%= Tour.find(params[:tour_id]).name %>" </h1>
<h3>It seems there are not enough seats to book the Tour!</h3>
<h3>Consider Wait List!!</h3>
<h2>Do you still want to book available seats and get remaining seats into Wait List?</h2>

<%= render 'form_with_waitlist', booking: @booking %>

<%= link_to 'Cancel', tours_url %> |
<%= link_to 'Back', my_bookings_path %>

app/views/bookings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Booked seats:</strong>
  <%= @booking.booked_seats %>
</p>

<p>
  <strong>Status:</strong>
  <%= @booking.find_booked_tour.show_status %>
</p>

<p>
  <strong>Tour name:</strong>
  <%= @booking.find_booked_tour.name %>
</p>

<p>
  <strong>Tour price:</strong>
  <%= @booking.find_booked_tour.price %>
</p>

<p>
  <strong>Tour start date:</strong>
  <%= @booking.find_booked_tour.start_date %>
</p>

<p>
  <strong>Tour end date:</strong>
  <%= @booking.find_booked_tour.end_date %>
</p>

<p>
  <strong>Available seats:</strong>
  <%= @booking.find_booked_tour.available_seats %>
</p>

<p>
  <strong>Your wait listed seats:</strong>
  <%= @booking.waitlist_seats %>
</p>

<p>
  <strong>Tour total seats:</strong>
  <%= @booking.find_booked_tour.total_seats %>
</p>

<p>
  <strong>Tour wait list seats:</strong>
  <%= @booking.find_booked_tour.get_waitlist %>
</p>

<p>
  <strong>Tour status:</strong>
  <%= @booking.find_booked_tour.show_status %>
</p>

<br>
<%= button_to 'Edit Booking', edit_booking_path(@booking), method: :get, params: { tour_id: @booking.find_booked_tour.id } %>
<%= button_to "Delete", @booking, method: :delete, data: { confirm: 'Are you sure Deleting Booking?' } %>
<br> <br>

<%= link_to 'Home', home_index_url %> |
<%= link_to 'Edit Booking', edit_booking_path(@booking, tour_id: @booking.find_booked_tour.id) %> |
<%= link_to 'View Booked Tour', @booking.find_booked_tour %> |
<%= link_to 'All Tours', tours_path %> |
<%= link_to 'Delete Booking', @booking, method: :delete, data: { confirm: 'Are you sure Deleting Booking?' } %> |
<%= link_to 'Back', my_bookings_url %>