config/routes.rb
Rails.application.routes.draw do
  resources :reviews
  get 'show_tour_review' => 'reviews#show_tour_review'
  resources :bookings
  get 'my_bookings' => 'bookings#my_bookings'
  get 'my_customers_booked' => 'bookings#my_customers_booked'
  get 'my_customers_bookmarked' => 'bookings#my_customers_bookmarked'
  get 'new_with_waitlist' => 'bookings#new_with_waitlist'
  get 'bookmark' => 'bookings#bookmark'
  get 'undo_bookmark' => 'bookings#undo_bookmark'
  get 'customer_bookmarks' => 'bookings#customer_bookmarks'
  get 'agent_bookmarks' => 'bookings#agent_bookmarks'
  resources :tours
  resources :tours do
    resources :reviews, except: [:show, :index]
    member do
      patch :cancel_tour
      put :cancel_tour
    end
  end
  get 'search' => 'tours#search'
  get 'image' => 'tours#image'

  get 'home/index'

  devise_for :users
  resources :users, except: :create
  post 'create_user' => 'users#create', as: :create_user
  get 'admin' => 'users#admin'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'home#index'
end

app/models/user.rb
class User < ApplicationRecord
  has_many :tours, dependent: :destroy
  has_many :bookings, dependent: :destroy
  has_many :reviews, dependent: :destroy

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  enum role: [:admin, :agent, :customer]

  validates :name, presence: true
  validates :email, format: { with: /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/,
                              message: "Email format is invalid" },
            uniqueness: { case_sensitive: false }, presence: true
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /admin
  # GET /admin.json
  def admin
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @users = User.find(params[:id])
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        flash[:danger] = @user.errors.full_messages.first
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation, :role)
    end

  private
  def admin_user
    redirect_to(root_url) unless current_user.admin?
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <br>

  <div class="field">
    <%= form.label :email %>
    <%= form.email_field :email, autofocus: true, autocomplete: "email" %>
  </div>

  <br>

  <div class="field">
    <%= form.label :password %>
    <i>(Admin unable to change it due to security reasons)</i><br />
  </div>


  <div class="field">
    <%= form.label :'User Role' %>
    <%= form.select :role, [['Agent', 'agent'], ['Customer', 'customer']] %>
  </div>

  <br>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/_new_form.html.erb
<h2>New sign up</h2>

<%= form_for User.new, url: create_user_path do |form| %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, autofocus: true, autocomplete: "name", value: "" %>
  </div>

  <br>

  <div class="field">
    <%= form.label :email %>
    <%= form.email_field :email, autofocus: true, autocomplete: "email", value: "" %>
  </div>

  <br>

  <div class="field">
    <%= form.label :password %>
    <em>(6 characters minimum)</em><br />
    <%= form.password_field :password, autocomplete: "new-password" %>
  </div>

  <br>

  <div class="field">
    <%= form.label :password_confirmation %>
    <%= form.password_field :password_confirmation, autocomplete: "new-password" %>
  </div>

  <br>

  <div class="field">
    <br>
    <%= form.label :'User Role' %>
    <%= form.select :role, [['Agent', 'agent'], ['Customer', 'customer']] %>
  </div>

  <br>

  <div class="actions">
    <%= form.submit "Sign up" %>
  </div>
<% end %>

app/views/users/admin.html.erb
<p id="notice"><%= notice %></p>
<% if current_user.admin? %>
  <br>
  <h1>Users section</h1>
  <p>Only for Admin purposes:</p>

  <%= link_to 'Create New User', new_user_url %>
  <br><br>
  <table>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Role</th>
      <th>Password</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>

    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= user.role %></td>
        <td>*****</td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <% if !user.admin? %>
          <td><%= link_to 'Delete', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </table>
  <%= button_to 'Create New User', new_user_url, method: :get %>
<% end %>

<br><br>

<%= link_to 'Home', home_index_url %> |
<%= link_to 'Back', users_url %>

app/views/users/edit.html.erb
<h1>Editing Profile: <%= @user.name %></h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Let's Get Started!</h1>

<h1>My Profile</h1>
<%= link_to 'Edit/Delete Profile', edit_user_registration_url %>

<% if current_user.admin? %>
  <h1>Users section</h1>
  Only for Admin purposes:<br>
  <%= link_to 'Create/View/Edit/Delete Users', admin_url %>
  <br>
<% end %>

<h1>Tours section</h1>
<% if current_user.admin? || current_user.agent? %>
  <%= link_to 'Create/View/Edit/Cancel/Delete Tours', tours_url %>
  <br>
<% end %>
<% if current_user.admin? || current_user.customer? %>
  <%= link_to 'View/Book Tours', tours_url %>
  <br>
<% end %>

<% if current_user.admin? || current_user.agent? %>
  <h1>My Customers section</h1>
  <%= link_to 'Who Booked My Tours', bookings_url %> |
  <%= link_to 'Who Bookmarked My Tours', agent_bookmarks_url %>
  <br>
<% end %>
<% if current_user.admin? || current_user.customer? %>
  <h1>My Reservations section</h1>
  <%= link_to 'My Bookings', my_bookings_url %> | <%= link_to 'My Bookmarks Page', customer_bookmarks_url %>
  <br>
<% end %>

<h1>Reviews section</h1>
<%= link_to 'Tours Reviews', reviews_url %>

<br>

<h1>Search section</h1>
<%= link_to 'Search Tour', search_url %>

<br><br><br>

<%= link_to 'Home', home_index_url %>

app/views/users/new.html.erb
<h1>Create New User</h1>

<%= render 'new_form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Role:</strong>
  <%= @user.role %>
</p>


<%= link_to 'Home', home_index_url %> |

<% if current_user.admin? || current_user.id == @user.id %>
  <%= link_to 'Edit', edit_user_path(@user) %> |
<% end %>
<%= link_to 'Back to My Customers', bookings_url(id: current_user.id) %> |
<%= link_to 'Back to Usear Page', users_path %>