config/routes.rb
Rails.application.routes.draw do
  resources :reviews
  get 'show_tour_review' => 'reviews#show_tour_review'
  resources :bookings
  get 'my_bookings' => 'bookings#my_bookings'
  get 'my_customers_booked' => 'bookings#my_customers_booked'
  get 'my_customers_bookmarked' => 'bookings#my_customers_bookmarked'
  get 'new_with_waitlist' => 'bookings#new_with_waitlist'
  get 'bookmark' => 'bookings#bookmark'
  get 'undo_bookmark' => 'bookings#undo_bookmark'
  get 'customer_bookmarks' => 'bookings#customer_bookmarks'
  get 'agent_bookmarks' => 'bookings#agent_bookmarks'
  resources :tours
  resources :tours do
    resources :reviews, except: [:show, :index]
    member do
      patch :cancel_tour
      put :cancel_tour
    end
  end
  get 'search' => 'tours#search'
  get 'image' => 'tours#image'

  get 'home/index'

  devise_for :users
  resources :users, except: :create
  post 'create_user' => 'users#create', as: :create_user
  get 'admin' => 'users#admin'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'home#index'
end

app/models/tour.rb
class Tour < ApplicationRecord
  belongs_to :user
  has_many :bookings, dependent: :destroy
  has_many :reviews, dependent: :destroy

  validates :name, :description, :deadline, :start_date, :end_date,
            :start_location, :country, :state, presence: true
  validates :total_seats, numericality: { only_integer: true, greater_than: 0 }, presence: true
  validates :price, numericality: true, presence: true
  validates :user_id, presence: true
  validate :start_date_after_deadline?
  validate :end_date_after_start_date?

  has_attached_file :image, styles: { large:"600x600>", medium:"300x300>", thumb:"150x150#"}
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/

  def end_date_after_start_date?
    if end_date < start_date
      errors.add :start_date, "Start date cannot be later End date"
    end
  end

  def start_date_after_deadline?
    if start_date < deadline
      errors.add :deadline, "Booking deadline date cannot be later Start date"
    end
  end

  def is_completed?
    self.end_date < Date.current
  end

  def is_ongoing?
    self.start_date <= Date.current && self.end_date >= Date.current
  end

  def show_agent_info
    user = User.find(self.user_id)
    "Name: #{user.name} Email: #{user.email}"
  end

  def show_status
    return "Canceled" if self.canceled
    return "Completed" if is_completed?
    return "On Going" if is_ongoing?
    "In Future"
  end

  def tour_requested_seats
    req_seats = 0
    Booking.where("tour_id = ?", self.id).find_each do |tour|
      req_seats += tour.booked_seats
    end
    req_seats
  end

  def available_seats
    self.total_seats - tour_requested_seats
  end

  def find_booking(current_user_id)
    Booking.find_by(user_id: current_user_id, tour_id: self.id)
  end

  def is_booked?(current_user_id)
    booking = find_booking(current_user_id)
    return false if booking.nil? || booking.booked_seats == 0
    true
  end

  def get_waitlist
    total_wait_seats = 0
    Booking.where("tour_id = ?", self.id).find_each do |wait_seats|
      total_wait_seats += wait_seats.waitlist_seats
    end
    total_wait_seats
  end

  def is_taken?(current_user_id)
    booking = find_booking(current_user_id)
    return false if booking.nil? || booking.booked_seats == 0
    true
  end

  def get_customer_review(current_user_id)
    Review.find_by(user_id: current_user_id, tour_id: self.id)
  end

  def get_review_id
    review = Review.find_by(tour_id: self.id)
    return nil if review.nil?
    review.id
  end

  def is_bookmarked?(current_user_id)
    booking = find_booking(current_user_id)
    booking.bookmark
  end

  # def self.search(search)
  #   if search
  #     where('name LIKE ?', "%#{search}%")
  #   else
  #     Tour.all
  #   end
  # end

end

app/controllers/tours_controller.rb
class ToursController < ApplicationController
  before_action :authenticate_user!
  before_action :set_tour, only: [:show, :edit, :update, :destroy, :cancel_tour]

  # GET /tours
  # GET /tours.json
  def index
    @tours = Tour.all
    if params[:search]
      @search = TourSearch.new(params[:search])
      @tours = @search.scope
      @tours = {} if @tours.nil?
    end
  end

  # GET /tours/1
  # GET /tours/1.json
  def show
    @tours = Tour.find(params[:id])
  end

  # GET /tours/new
  def new
    @tour = Tour.new
  end

  # GET /tours/1/edit
  def edit
  end

  # POST /tours
  # POST /tours.json
  def create
    @tour = Tour.new(tour_params)
    @tour.user_id = current_user.id
    respond_to do |format|
      if @tour.save
        format.html { redirect_to @tour, notice: 'Tour was successfully created.' }
        format.json { render :show, status: :created, location: @tour }
      else
        format.html { render :new }
        format.json { render json: @tour.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tours/1
  # PATCH/PUT /tours/1.json
  def update
    respond_to do |format|
      if @tour.update(tour_params)
        booking = Booking.find_by(tour_id: @tour.id)
        booking.fill_available_seats unless booking.nil?
        format.html { redirect_to @tour, notice: 'Tour was successfully updated.' }
        format.json { render :show, status: :ok, location: @tour }
      else
        format.html { render :edit }
        format.json { render json: @tour.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tours/1
  # DELETE /tours/1.json
  def destroy
    @tour.destroy
    respond_to do |format|
      format.html { redirect_to tours_url, notice: 'Tour was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def cancel_tour
    @tour.update_attribute(:canceled, true)
    respond_to do |format|
      if @tour.save
        format.html { redirect_to @tour, notice: 'Tour was successfully Cancelled.' }
        format.json { render :show, status: :created, location: @tour }
      else
        format.html { render :new }
        format.json { render json: @tour.errors, status: :unprocessable_entity }
      end
    end
  end

  # GET /search
  # GET /search.json
  def search
    @search = TourSearch.new(params[:search])
    @tours = @search.scope
  end

  # GET /image
  # GET /image.json
  def image
    @tour = Tour.find(params[:tour_id])
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tour
      @tour = Tour.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tour_params
      params.require(:tour).permit(:name, :description, :price, :image, :deadline, :start_date, :end_date, :start_location, :country, :state, :total_seats, :canceled, :user_id, :search)
    end
end

app/helpers/tours_helper.rb
module ToursHelper
end

app/views/tours/_form.html.erb
<%= form_with(model: tour, html: { multipart: true }, local: true) do |form| %>
  <% if tour.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(tour.errors.count, "error") %> prohibited this tour from being saved:</h2>

      <ul>
      <% tour.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.text_field :price %>
  </div>

  <div class="field">
    <%= form.label :image %>
    <%= form.file_field :image %>
  </div>

  <div class="field">
    <%= form.label :deadline %>
    <%= form.date_select :deadline %>
  </div>

  <div class="field">
    <%= form.label :start_date %>
    <%= form.date_select :start_date %>
  </div>

  <div class="field">
    <%= form.label :end_date %>
    <%= form.date_select :end_date %>
  </div>

  <div class="field">
    <%= form.label :start_location %>
    <%= form.text_field :start_location %>
  </div>

  <div class="field">
    <%= form.label 'Countries itinerary' %>
    <%= form.text_area :country %>
  </div>

  <div class="field">
    <%= form.label 'State itinerary' %>
    <%= form.text_area :state %>
  </div>

  <div class="field">
    <%= form.label :total_seats %>
    <%= form.number_field :total_seats %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/tours/edit.html.erb
<h1>Editing Tour</h1>

<%= render 'form', tour: @tour %>

<% if current_user.admin? || (current_user.agent? && !@tour.is_completed? && !@tour.canceled) %>
  <%= button_to "Cancel", cancel_tour_tour_path(@tour), method: :put, data: { confirm: 'Are you sure Cancelling Tour?' } %>
  <br> <br>
<% end %>

<%= link_to 'Show', @tour %> |
<%= link_to 'Back', tours_path %>

app/views/tours/image.html.erb
<p id="notice"><%= notice %></p>
<h1>Tour Image</h1>
<%= image_tag @tour.image.url(:large) %>

<br><br>

<%= link_to 'Home', home_index_url %> |
<%= link_to 'Back', @tour %>

app/views/tours/index.html.erb
<p id="notice"><%= notice %></p>

<%= form_tag(bookmark_url, method: :get)  do %>
  <h1>Tours</h1>

  <table>
    <thead>
      <tr>
        <% if current_user.customer? || current_user.admin? %>
          <th>Bookmark</th>
        <% end %>
        <th>Name</th>
        <th>Price</th>
        <th>Start date</th>
        <th>Start location</th>
        <th>Available seats</th>
        <th>Wait list</th>
        <th>Total seats</th>
        <th>Status</th>
        <th colspan="3"></th>
      </tr>
    </thead>


    <tbody>
      <% @tours.each do |tour| %>
        <tr>
          <% if current_user.customer? || current_user.admin? %>
            <td><%= check_box_tag 'tour_id[]', tour.id %></td>
          <% end %>
          <td><%= tour.name %></td>
          <td><%= tour.price %></td>
          <td><%= tour.start_date %></td>
          <td><%= tour.start_location %></td>
          <td><%= tour.available_seats %></td>
          <td><%= tour.get_waitlist %></td>
          <td><%= tour.total_seats %></td>
          <td><%= tour.show_status %></td>
          <td><%= link_to 'Details', tour %></td>
          <% if current_user.admin? || (current_user.agent? && current_user.id == tour.user_id) %>
            <td><%= link_to 'My Customers booked', my_customers_booked_url(tour_id: tour.id) %></td>
            <td><%= link_to 'My Customers bookmarked', my_customers_bookmarked_url(tour_id: tour.id) %></td>
            <td><%= link_to 'Edit', edit_tour_path(tour) %></td>
            <% if !tour.is_completed? && !tour.canceled %>
              <td><%= link_to 'Cancel', cancel_tour_tour_url(tour), method: :put, data: { confirm: 'Are you sure Cancelling Tour?' } %></td>
            <% end %>
            <td><%= link_to 'Delete', tour, method: :delete, data: { confirm: 'Are you sure Deleting Tour?' } %></td>
          <% end %>
          <% if current_user.admin? || (current_user.customer? && !tour.is_completed? && !tour.is_ongoing? && !tour.canceled && !tour.is_booked?(current_user.id)) %>
            <td><%= link_to 'Book Tour', new_booking_path(tour_id: tour.id) %></td>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>

  <% if current_user.customer? || current_user.admin? %>
    <%= submit_tag 'Bookmark!' %>
    <br><br>
  <% end %>
<% end %>

<br>

<% if current_user.agent? || current_user.admin? %>
  <%= button_to 'Create Tour', new_tour_url, method: :get %>
  <br><br>
<% end %>

<%= link_to 'Home', home_index_url %> |

<% if current_user.agent? || current_user.admin? %>
  <%= link_to 'Create New Tour', new_tour_path %> |
  <%= link_to 'List All My Customers', bookings_url(id: current_user.id) %> |
  <%= link_to 'List Customers with Bookmarks', agent_bookmarks_url %> |
<% end %>

<% if current_user.customer? || current_user.admin? %>
  <td><%= link_to 'My Booked Tours', my_bookings_url %></td> |
  <td><%= link_to 'My Bookmarks', customer_bookmarks_url %></td> |
<% end %>
<%= link_to 'Search Tour', search_url %> |
<td><%= link_to 'Back to User page', users_url %></td>

app/views/tours/new.html.erb
<h1>New Tour</h1>

<%= render 'form', tour: @tour %>

<%= link_to 'Back', tours_path %>

app/views/tours/search.html.erb
<p id="notice"><%= notice %></p>
  <h1>Search Tours</h1>
    <%= form_tag(tours_path, method: :get) do %>
      <h3>Search by name:</h3>
      <%= text_field_tag 'search[tour_name]', @search.tour_name %> <br>
      <%= submit_tag ("Search") %>

      <h3>Search by dates (YYYY-MM-DD, example 2019-02-22):</h3>
      <p>From:</p><%= text_field_tag 'search[date_from]', @search.date_from %>
      <br>
      <p>To:</p><%= text_field_tag 'search[date_to]', @search.date_to %> <br>
      <%= submit_tag ("Search") %>

      <h3>Search by price:</h3>
      <p>Min:</p><%= text_field_tag 'search[price_from]', @search.price_from %>
      <br>
      <p>Max:</p><%= text_field_tag 'search[price_to]', @search.price_to %> <br>
      <%= submit_tag ("Search") %>

      <h3>Search by seats availability: </h3>
      <%= text_field_tag 'search[seats]', @search.seats %> <br>
      <%= submit_tag ("Search") %>

      <h3>Search by tour itinerary: </h3>
      <%= text_field_tag 'search[location]', @search.location %> <br>
      <%= submit_tag ("Search") %>

    <% end %>

<br><br>

<%= link_to 'Home', home_index_url %> |
<% if current_user.agent? || current_user.admin? %>
  <%= link_to 'Create New Tour', new_tour_path %> |
  <%= link_to 'List All My Customers', bookings_url(id: current_user.id) %> |
  <%= link_to 'List Customers with Bookmarks', agent_bookmarks_url %> |
<% end %>

<% if current_user.customer? || current_user.admin? %>
  <td><%= link_to 'My Booked Tours', my_bookings_url %></td> |
  <td><%= link_to 'My Bookmarks', customer_bookmarks_url %></td> |
<% end %>

<td><%= link_to 'Back to User page', users_url %></td>

app/views/tours/show.html.erb
<p id="notice"><%= notice %></p>
<%= form_tag(bookmark_url, method: :get)  do %>

  <% if current_user.customer? || current_user.admin? %>
    <p>
      <strong>Bookmark:</strong>
      <%= check_box_tag 'tour_id[]', @tour.id %>
      <%= submit_tag 'Bookmark!' %>
    </p>
  <% end %>

  <p>
    <strong>Name:</strong>
    <%= @tour.name %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= @tour.description %>
  </p>

  <p>
    <strong>Price:</strong>
    <%= @tour.price %>
  </p>

  <p>
    <strong>Image:</strong>
    <%= link_to "View Image", image_url(tour_id: @tour.id) %>
  </p>

  <p>
    <strong>Deadline:</strong>
    <%= @tour.deadline %>
  </p>

  <p>
    <strong>Start date:</strong>
    <%= @tour.start_date %>
  </p>

  <p>
    <strong>End date:</strong>
    <%= @tour.end_date %>
  </p>

  <p>
    <strong>Start location:</strong>
    <%= @tour.start_location %>
  </p>

  <p>
    <strong>Countries itinerary:</strong>
    <%= @tour.country %>
  </p>

  <p>
    <strong>States itinerary:</strong>
    <%= @tour.state %>
  </p>

  <p>
    <strong>Available seats:</strong>
    <%= @tour.available_seats %>
  </p>

  <p>
    <strong>Wait list:</strong>
    <%= @tour.get_waitlist %>
  </p>

  <p>
    <strong>Total seats:</strong>
    <%= @tour.total_seats %>
  </p>

  <p>
    <strong>Status:</strong>
    <%= @tour.show_status %>
  </p>

  <p>
    <strong>Contact information:</strong>
    <%= @tour.show_agent_info %>
  </p>
<% end %>

<br>

<% if current_user.admin? || (current_user.agent? && current_user.id == @tour.user_id && !@tour.is_completed? && !@tour.canceled) %>
  <%= button_to "Cancel", cancel_tour_tour_path(@tour), method: :put, data: { confirm: 'Are you sure Cancelling Tour?' } %>
<% end %>
<% if current_user.admin? || (current_user.agent? && current_user.id == @tour.user_id) %>
  <%= button_to 'Edit', edit_tour_path(@tour), method: :get %>
  <%= button_to "Booked Customers", my_customers_booked_url, method: :get, params: {tour_id: @tour.id} %>
  <%= button_to "Bookmarked Customers", my_customers_bookmarked_url, method: :get, params: {tour_id: @tour.id} %>
  <br>
  <%= button_to 'Delete', @tour, method: :delete, data: { confirm: 'Are you sure Deleting Tour?' } %>
  <br><br>
<% end %>

<% if current_user.admin? || (current_user.customer? && !@tour.is_completed? && !@tour.canceled && !@tour.is_booked?(current_user.id)) %>
  <%= button_to "Book", new_booking_url, method: :get, params: {tour_id: @tour.id} %>
  <br><br>
<% end %>


<h2>Reviews:</h2>
<% if @tour.show_status == "Completed" %>
  <% if current_user.admin? || (current_user.customer? && @tour.is_taken?(current_user.id)) %>
    <% if @tour.get_customer_review(current_user.id).nil? %>
      <%= button_to "Write Review", new_tour_review_url(@tour.id), method: :get %>
    <% else %>
      <%= button_to "Your Review", @tour.get_customer_review(current_user.id), method: :get %>
      <%= button_to "Edit Review", edit_tour_review_url(@tour, @tour.get_customer_review(current_user.id)), method: :get %>
      <%= button_to 'Destroy', @tour.get_customer_review(current_user.id), method: :delete, data: { confirm: 'Are you sure Deleting Review?' } %>
    <% end %>
    <br>
  <% end %>
  <%= button_to "View Reviews", show_tour_review_url, method: :get, params: { tour_id: @tour.id} %>
<% else %>
  <p>Reviews for this Tour are unavailable since it has not been Completed</p>
<% end %>

<br><br>

<%= link_to 'Home', home_index_url %> |
<% if current_user.admin? || (current_user.customer? && !@tour.is_completed? && !@tour.canceled && !@tour.is_booked?(current_user.id)) %>
  <%= link_to 'Book Tour', new_booking_path(tour_id: @tour.id) %> |
<% end %>
<% if current_user.admin? || (current_user.agent? && current_user.id == @tour.user_id) %>
  <%= link_to "Booked Customers", my_customers_booked_url(tour_id: @tour.id) %> |
  <%= link_to "Bookmarked Customers", my_customers_bookmarked_url(tour_id: @tour.id) %> |
<% end %>
<% if @tour.show_status == "Completed" %>
  <%= link_to "View Reviews", show_tour_review_url(tour_id: @tour.id) %> |
<% end %>
<% if current_user.admin? || (current_user.agent? && current_user.id == @tour.user_id) %>
  <%= link_to 'Back to My Customers', bookings_url(id: current_user.id) %> |
  <%= link_to 'Edit', edit_tour_path(@tour) %> |
  <% if !@tour.is_completed? && !@tour.canceled %>
    <%= link_to 'Cancel', cancel_tour_tour_path(@tour), method: :put, data: { confirm: 'Are you sure Cancelling Tour?' } %> |
  <% end %>
  <%= link_to 'Delete', @tour, method: :delete, data: { confirm: 'Are you sure Deleting Tour?' } %> |
<% end %>

<%= link_to 'Search Tour', search_url %> |
<%= link_to 'Back to Tours', tours_path %>