config/routes.rb
Rails.application.routes.draw do
  resources :reviews
  get 'show_tour_review' => 'reviews#show_tour_review'
  resources :bookings
  get 'my_bookings' => 'bookings#my_bookings'
  get 'my_customers_booked' => 'bookings#my_customers_booked'
  get 'my_customers_bookmarked' => 'bookings#my_customers_bookmarked'
  get 'new_with_waitlist' => 'bookings#new_with_waitlist'
  get 'bookmark' => 'bookings#bookmark'
  get 'undo_bookmark' => 'bookings#undo_bookmark'
  get 'customer_bookmarks' => 'bookings#customer_bookmarks'
  get 'agent_bookmarks' => 'bookings#agent_bookmarks'
  resources :tours
  resources :tours do
    resources :reviews, except: [:show, :index]
    member do
      patch :cancel_tour
      put :cancel_tour
    end
  end
  get 'search' => 'tours#search'
  get 'image' => 'tours#image'

  get 'home/index'

  devise_for :users
  resources :users, except: :create
  post 'create_user' => 'users#create', as: :create_user
  get 'admin' => 'users#admin'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'home#index'
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_review, only: [:show, :edit, :update, :destroy]
  before_action :set_tour

  # GET /reviews
  # GET /reviews.json
  def index
    @reviews = Review.all
  end

  # GET /reviews/1
  # GET /reviews/1.json
  def show
    @reviews = Review.find(params[:id])
  end

  # GET /reviews/new
  def new
    @review = Review.new
  end

  # GET /reviews/1/edit
  def edit
  end

  # POST /reviews
  # POST /reviews.json
  def create
    @review = Review.new(review_params)
    @review.user_id = current_user.id
    @review.tour_id = @tour.id

    respond_to do |format|
      if @review.save
        format.html { redirect_to @tour, notice: 'Review was successfully created.' }
        format.json { render :show, status: :created, location: @review }
      else
        format.html { render :new }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reviews/1
  # PATCH/PUT /reviews/1.json
  def update
    respond_to do |format|
      if @review.update(review_params)
        format.html { redirect_to @tour, notice: 'Review was successfully updated.' }
        format.json { render :show, status: :ok, location: @review }
      else
        format.html { render :edit }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reviews/1
  # DELETE /reviews/1.json
  def destroy
    @review.destroy
    respond_to do |format|
      format.html { redirect_to reviews_url, notice: 'Review was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  # GET /show_tour_review/1
  # GET /show_tour_review/1.json
  def show_tour_review
    @reviews = Review.where(tour_id: params[:tour_id])
    @tour = Tour.find_by(id: params[:tour_id])
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_review
      @review = Review.find(params[:id])
    end

    def set_tour
      if params[:tour_id].nil? || params[:tour_id].blank?
        @tour = nil
      else
        @tour = Tour.find(params[:tour_id])
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def review_params
      params.require(:review).permit(:rating, :subject, :content, :user_id)
    end
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/reviews/_form.html.erb
<%= form_for([@tour, @review]) do |form| %>
  <% if @review.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@review.errors.count, "error") %> prohibited this review from being saved:</h2>

      <ul>
      <% @review.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label 'Rating (0 - 10)' %>
    <%= form.number_field :rating %>
  </div>

  <div class="field">
    <%= form.label :subject %>
    <%= form.text_field :subject %>
  </div>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/reviews/edit.html.erb
<h1>Editing Review</h1>

<%= render 'form'%>

<%= link_to 'Back to Tour', @tour %>

app/views/reviews/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Reviews</h1>

<table>
  <thead>
    <tr>
      <th>Customer name</th>
      <th>Customer email</th>
      <th>Tour Name</th>
      <th>Rating</th>
      <th>Subject</th>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @reviews.each do |review| %>
      <tr>
        <% if current_user.admin? || (current_user.agent? && current_user.id == review.get_tour_agent_id) || (current_user.customer? && review.is_reviewed?(current_user.id)) %>
          <td><%= review.get_customer_name %></td>
          <td><%= review.get_customer_email %></td>
        <% else %>
          <td>*****</td>
          <td>*****</td>
        <% end %>
        <td><%= review.find_booked_tour.name %></td>
        <td><%= review.rating %></td>
        <td><%= review.subject %></td>
        <td><%= review.content %></td>
        <td><%= link_to 'Details', review %></td>
        <% if current_user.admin? || (current_user.customer? && review.is_reviewed?(current_user.id)) %>
          <td><%= link_to 'Edit', edit_review_path(review) %></td>
          <td><%= link_to 'Destroy', review, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Home', home_index_url %> |
<%= link_to 'Back to Tours', tours_url %>

app/views/reviews/new.html.erb
<h1>New Review</h1>

<%= render 'form', review: @review %>

<%= link_to 'Back to Tour', @tour %>

app/views/reviews/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Rating:</strong>
  <%= @review.rating %>
</p>

<p>
  <strong>Subject:</strong>
  <%= @review.subject %>
</p>

<p>
  <strong>Content:</strong>
  <%= @review.content %>
</p>

<p>
	<strong>Customer name:</strong>
  <% if current_user.admin? || (current_user.agent? && current_user.id == @review.get_tour_agent_id) || (current_user.customer? && @review.is_reviewed?(current_user.id)) %>
	  <%= @review.get_customer_name %>
  <% else %>
    *****
  <% end %>
</p>

<p>
	<strong>Customer Email</strong>
  <% if current_user.admin? || (current_user.agent? && current_user.id == @review.get_tour_agent_id) || (current_user.customer? && @review.is_reviewed?(current_user.id)) %>
    <%= @review.get_customer_email %>
  <% else %>
    *****
  <% end %>
</p>
<% if current_user.admin? || (current_user.customer? && @review.is_reviewed?(current_user.id)) %>
  <%= link_to 'Edit', edit_review_path(@review) %> |
  <%= link_to 'Destroy', @review, method: :delete, data: { confirm: 'Are you sure?' } %> |
<% end %>
<%= link_to 'Back to Tour', @review.find_booked_tour %> |
<%= link_to 'Back to Reviews', reviews_path %>

app/views/reviews/show_tour_review.html.erb
<p id="notice"><%= notice %></p>

<h1>Reviews for the Tour <%= @tour.name %></h1>

<table>
  <thead>
    <tr>
      <th>Customer name</th>
      <th>Customer email</th>
      <th>Tour Name</th>
      <th>Rating</th>
      <th>Subject</th>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @reviews.each do |review| %>
      <tr>
        <% if current_user.admin? || (current_user.agent? && current_user.id == review.get_tour_agent_id) || (current_user.customer? && review.is_reviewed?(current_user.id)) %>
          <td><%= review.get_customer_name %></td>
          <td><%= review.get_customer_email %></td>
        <% else %>
          <td>*****</td>
          <td>*****</td>
        <% end %>
        <td><%= @tour.name %></td>
        <td><%= review.rating %></td>
        <td><%= review.subject %></td>
        <td><%= review.content %></td>
        <td><%= link_to 'Details', review %></td>
        <% if current_user.admin? || (current_user.customer? && review.is_reviewed?(current_user.id)) %>
          <td><%= link_to 'Edit', edit_review_path(review) %></td>
          <td><%= link_to 'Destroy', review, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br><br>

<%= link_to 'Back to Tour', @tour %>